// productsData.js
export const sampleProducts = [
  {
    id: 1,
    name: "Kuya Wil 4s",
    category: ["Shoes", "Sneakers"],
    status: "In-stock",
    date: "2023-11-08",
    image: "images/shoes/product-image-1.jpg",
    price: "1200",
    cart: true,
  },
  {
    id: 2,
    name: "Vic Sotto Box Logo",
    category: ["Tops", "T-Shirt"],
    status: "In-stock",
    date: "2023-11-09",
    image: "product-image-2.jpg",
    price: "2900",
    cart: true,
  },
  {
    id: 3,
    name: "Very Very short Shorts",
    category: ["Bottoms", "Shorts"],
    status: "Out of Stock",
    date: "2023-11-09",
    image: "product-image-2.jpg",
    price: "650",
    cart: true,
  },
  {
    id: 4,
    name: "Vintage Look Sandals",
    category: ["Shoes", "Sandals"],
    status: "Out of Stock",
    date: "2023-11-09",
    image: "product-image-2.jpg",
    price: "999",
    cart: false,
  },
  {
    id: 5,
    name: "Pink Crop Top",
    category: ["Tops", "Crop Top"],
    status: "In-stock",
    date: "2023-11-09",
    image: "product-image-2.jpg",
    price: "205",
    cart: true,
  },
];
