// productsData.js

export const sampleProducts = [
  {
    id: 1,
    name: "Kuya Wil 4s",
    category: ["Shoes", "Sneakers"],
    status: "In-stock",
    date: "2023-11-08",
    image: "images/shoes/product-image-1.jpg",
    price: "1200.00",
    salesData: "50", 
    cart: true,
  },
  {
    id: 2,
    name: "Vic Sotto Box Logo",
    category: ["Tops", "T-Shirt"],
    status: "In-stock",
    date: "2023-11-09",
    image: "images/shoes/product-image-1.jpg",
    price: "2900.00",
    salesData: "35", 

    cart: true,
  },
  {
    id: 3,
    name: "Ribbed Top",
    category: ["Tops", "Crop Top"],
    status: "Out of Stock",
    date: "2023-11-09",
    image: "images/shoes/product-image-1.jpg",
    price: "650.00",
    salesData: "50", 
    cart: true,
  },
  {
    id: 4,
    name: "Vintage Look Sandals",
    category: ["Shoes", "Sandals"],
    status: "Out of Stock",
    date: "2023-11-09",
    image: "images/shoes/product-image-1.jpg",
    price: "999.25",
    salesData: "78", 
    cart: false,
  },
  {
    id: 5,
    name: "Pink Crop Top",
    category: ["Tops", "Crop Top"],
    status: "In-stock",
    date: "2023-11-09",
    image: "images/shoes/product-image-1.jpg",
    price: "205.36",
    salesData: "10", 
    cart: true,
  },
  {
    id: 6,
    name: "Nike Air Max1",
    category: ["Shoes", "Sneakers"],
    status: "In-stock",
    date: "2023-11-09",
    image: "images/shoes/product-image-1.jpg",
    price: "205.36",
    salesData: "20", 
    cart: true,
  },
  {
    id: 7,
    name: "Round Neck Shirt",
    category: ["Tops", "T-Shirt"],
    status: "In-stock",
    date: "2023-11-09",
    image: "images/shoes/product-image-1.jpg",
    price: "205.36",
    salesData: "90", 
    cart: true,
  },
  {
    id: 8,
    name: "Flare Pants",
    category: ["Bottoms", "Pants"],
    status: "In-stock",
    date: "2023-11-09",
    image: "images/shoes/product-image-1.jpg",
    price: "205.36",
    salesData: "110", 
    cart: true,
  },
  {
    id: 9,
    name: "Flare Jeans",
    category: ["Bottoms", "Pants"],
    status: "In-stock",
    date: "2023-11-09",
    image: "images/shoes/product-image-1.jpg",
    price: "205.36",
    salesData: "60", 
    cart: true,
  },
  {
    id: 10,
    name: "Cargo Shorts",
    category: ["Bottoms", "Shorts"],
    status: "In-stock",
    date: "2023-11-09",
    image: "images/shoes/product-image-1.jpg",
    price: "205.36",
    salesData: "80", 
    cart: true,
  },
  {
    id: 11,
    name: "Polo Shirt",
    category: ["Tops", "T-Shirt"],
    status: "In-stock",
    date: "2023-11-09",
    image: "images/shoes/product-image-1.jpg",
    price: "205.36",
    salesData: "5", 
    cart: true,
  },
  {
    id: 12,
    name: "Brown Boots",
    category: ["Shoes", "Boots"],
    status: "In-stock",
    date: "2023-11-09",
    image: "images/shoes/product-image-1.jpg",
    price: "205.36",
    salesData: "150", 
    cart: true,
  },

];
